# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ez_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(421, 545)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(400, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_1 = QtGui.QVBoxLayout()
        self.verticalLayout_1.setObjectName(_fromUtf8("verticalLayout_1"))
        self.horizontalLayout_1 = QtGui.QHBoxLayout()
        self.horizontalLayout_1.setObjectName(_fromUtf8("horizontalLayout_1"))
        self.label_1 = QtGui.QLabel(self.centralwidget)
        self.label_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.horizontalLayout_1.addWidget(self.label_1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_1.addWidget(self.label_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem1)
        self.fileAddButton = QtGui.QPushButton(self.centralwidget)
        self.fileAddButton.setObjectName(_fromUtf8("fileAddButton"))
        self.horizontalLayout_1.addWidget(self.fileAddButton)
        self.verticalLayout_1.addLayout(self.horizontalLayout_1)
        self.fileSelectLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.fileSelectLineEdit.setToolTip(_fromUtf8("File may be dropped here"))
        self.fileSelectLineEdit.setObjectName(_fromUtf8("fileSelectLineEdit"))
        self.verticalLayout_1.addWidget(self.fileSelectLineEdit)
        self.verticalLayout.addLayout(self.verticalLayout_1)
        spacerItem2 = QtGui.QSpacerItem(400, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.validateLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.validateLineEdit.setToolTip(_fromUtf8("Published checksum value to compare against.\n"
"(Right click or \'Ctrl + V\' to paste)"))
        self.validateLineEdit.setText(_fromUtf8(""))
        self.validateLineEdit.setObjectName(_fromUtf8("validateLineEdit"))
        self.verticalLayout_2.addWidget(self.validateLineEdit)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem4 = QtGui.QSpacerItem(400, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.goButton = QtGui.QPushButton(self.centralwidget)
        self.goButton.setEnabled(False)
        self.goButton.setObjectName(_fromUtf8("goButton"))
        self.horizontalLayout_3.addWidget(self.goButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtGui.QSpacerItem(400, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem6)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.resultTextBrowser = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultTextBrowser.sizePolicy().hasHeightForWidth())
        self.resultTextBrowser.setSizePolicy(sizePolicy)
        self.resultTextBrowser.setMinimumSize(QtCore.QSize(0, 0))
        self.resultTextBrowser.setTabStopWidth(80)
        self.resultTextBrowser.setObjectName(_fromUtf8("resultTextBrowser"))
        self.verticalLayout_3.addWidget(self.resultTextBrowser)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_3.addWidget(self.progressBar)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.hashChoiceButton = QtGui.QComboBox(self.centralwidget)
        self.hashChoiceButton.setToolTip(_fromUtf8("Hash algorithm is selected automatically\n"
"if optional \'Validation\' text set"))
        self.hashChoiceButton.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.hashChoiceButton.setObjectName(_fromUtf8("hashChoiceButton"))
        self.hashChoiceButton.addItem(_fromUtf8(""))
        self.hashChoiceButton.addItem(_fromUtf8(""))
        self.hashChoiceButton.addItem(_fromUtf8(""))
        self.hashChoiceButton.addItem(_fromUtf8(""))
        self.hashChoiceButton.addItem(_fromUtf8(""))
        self.hashChoiceButton.addItem(_fromUtf8(""))
        self.hashChoiceButton.addItem(_fromUtf8(""))
        self.hashChoiceButton.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.hashChoiceButton)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.cancelButton = QtGui.QPushButton(self.centralwidget)
        self.cancelButton.setEnabled(False)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.horizontalLayout_4.addWidget(self.cancelButton)
        self.resetButton = QtGui.QPushButton(self.centralwidget)
        self.resetButton.setEnabled(False)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.horizontalLayout_4.addWidget(self.resetButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSelect_File = QtGui.QAction(MainWindow)
        self.actionSelect_File.setObjectName(_fromUtf8("actionSelect_File"))
        self.actionSave_Result = QtGui.QAction(MainWindow)
        self.actionSave_Result.setObjectName(_fromUtf8("actionSave_Result"))
        self.actionUser_Manual = QtGui.QAction(MainWindow)
        self.actionUser_Manual.setObjectName(_fromUtf8("actionUser_Manual"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionSelect_File)
        self.menuFile.addAction(self.actionSave_Result)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionUser_Manual)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.hashChoiceButton.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "EZ Checksum", None))
        self.label_1.setText(_translate("MainWindow", "1)", None))
        self.label_2.setText(_translate("MainWindow", "Select the file to test.", None))
        self.fileAddButton.setToolTip(_translate("MainWindow", "Select file to test", None))
        self.fileAddButton.setText(_translate("MainWindow", "Select File", None))
        self.fileSelectLineEdit.setStatusTip(_translate("MainWindow", "No file selected", None))
        self.fileSelectLineEdit.setPlaceholderText(_translate("MainWindow", "File to test", None))
        self.label_3.setText(_translate("MainWindow", "2)", None))
        self.label_4.setText(_translate("MainWindow", "Enter the expected value.", None))
        self.validateLineEdit.setStatusTip(_translate("MainWindow", "No validation text entered", None))
        self.validateLineEdit.setPlaceholderText(_translate("MainWindow", "Validation (Optional)", None))
        self.label_5.setText(_translate("MainWindow", "3)", None))
        self.label_6.setText(_translate("MainWindow", "Click the \'Start\' button.", None))
        self.goButton.setToolTip(_translate("MainWindow", "Select file first", None))
        self.goButton.setStatusTip(_translate("MainWindow", "No file selected", None))
        self.goButton.setText(_translate("MainWindow", "Start", None))
        self.label_7.setText(_translate("MainWindow", "Test results below:", None))
        self.resultTextBrowser.setToolTip(_translate("MainWindow", "Output window", None))
        self.progressBar.setStatusTip(_translate("MainWindow", "Not running", None))
        self.hashChoiceButton.setStatusTip(_translate("MainWindow", "Current algorithm: SHA-256", None))
        self.hashChoiceButton.setItemText(0, _translate("MainWindow", "MD5", None))
        self.hashChoiceButton.setItemText(1, _translate("MainWindow", "SHA-1", None))
        self.hashChoiceButton.setItemText(2, _translate("MainWindow", "SHA-224", None))
        self.hashChoiceButton.setItemText(3, _translate("MainWindow", "SHA-256", None))
        self.hashChoiceButton.setItemText(4, _translate("MainWindow", "SHA-384", None))
        self.hashChoiceButton.setItemText(5, _translate("MainWindow", "SHA-512", None))
        self.hashChoiceButton.setItemText(6, _translate("MainWindow", "XXH32", None))
        self.hashChoiceButton.setItemText(7, _translate("MainWindow", "XXH64", None))
        self.cancelButton.setToolTip(_translate("MainWindow", "Stop processing", None))
        self.cancelButton.setText(_translate("MainWindow", "Cancel", None))
        self.resetButton.setToolTip(_translate("MainWindow", "Reset all", None))
        self.resetButton.setText(_translate("MainWindow", "Reset", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help", None))
        self.actionSelect_File.setText(_translate("MainWindow", "Select File...", None))
        self.actionSave_Result.setText(_translate("MainWindow", "Save Result...", None))
        self.actionUser_Manual.setText(_translate("MainWindow", "Manual...", None))
        self.actionAbout.setText(_translate("MainWindow", "About...", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

